
language: java

jdk:
  - oraclejdk8

before_install:
   - mvn --version

install:
  # install without any testing
  - mvn install -U -Dmaven.test.skip=true -B -V -q -T4 -C

script:
  # execute unit and integration tests
  - mvn -e verify -B
  
after_success:
  - bash <(curl -s https://codecov.io/bash)  
  
os:
  - linux
  - windows
  - osx

osx_image: 
  - xcode7.3

cache:
  directories:
  - $HOME/.m2

branches:
  only:
  - master

notifications:
  email:
  - saptarshi.devnath@gmail.com
